const constants = {
    ADD_DAY: 'ADD_DAY',
    REMOVE_DAY: 'REMOVE_DAT',
    SET_GOAL: "SET_GOAL",
    ADD_ERROR: "ADD_ERROR",
    CLEAR_ERROR: "CLEAR_ERROR",
    FETCH_RESORT_NAMES: "FETCH_RESORT_NAMES",
    CANCEL_FETCHING: "CANCEL_FETCHING",
    CHANGE_SUGGESTIONS: "CHANGE_SUGGESTIONS",
    CLEAR_SUGGESTIONS: "CLEAR_SUGGESTIONS"
}
// constants.ADD_DAY - store all action in hash

export default constants
